openapi: 3.0.1
info:
  title: eleusish-api
  description: API for Eleusish game
  version: 1.0.0
servers:
- url: /api/v1
tags:
- name: Rules
  description: Game rules endpoints
- name: Specification
  description: The swagger API specification
paths:
  /rules:
    get:
      tags:
      - Rules
      description: Fetch all rules
      responses:
        200:
          description: Returns all rules
          content: {}
    post:
      tags:
      - Rules
      description: Create a new rule
      requestBody:
        description: a rule
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RuleBody'
        required: true
      responses:
        200:
          description: Returns all rules
          content: {}
  /rules/{id}:
    get:
      tags:
      - Rules
      parameters:
      - name: id
        in: path
        description: The id of the rule to retrieve
        required: true
        schema:
          type: string
      responses:
        200:
          description: Return the rule with the specified id
          content: {}
        404:
          description: Rule not found
          content: {}
  /spec:
    get:
      tags:
      - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    RuleBody:
      title: code
      required:
      - code
      type: object
      properties:
        code:
          type: string
          example: function getInitialCards (remainingCards) { return []; }; function isValid (previousCards, newCard) { return true; };
